"""phase 5 tally_sync_log

Revision ID: 29cad067d67e
Revises: 5c8691f7c311
Create Date: 2026-07-22 04:28:41.147915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '29cad067d67e'
down_revision: Union[str, None] = '5c8691f7c311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tally_sync_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tally_sync_log')
    # ### end Alembic commands ###
