"""phase 4 website tables

Revision ID: 5c8691f7c311
Revises: d5c1f027e9a2
Create Date: 2026-07-21 20:47:54.421219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c8691f7c311'
down_revision: Union[str, None] = 'd5c1f027e9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_paths', sa.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('client_name', sa.Text(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('website_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo_bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('machinery_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['machinery_id'], ['machinery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('website_order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('price_at_order', sa.Numeric(asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['website_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_order_items')
    op.drop_table('demo_bookings')
    op.drop_table('website_orders')
    op.drop_table('completed_projects')
    # ### end Alembic commands ###
